<?xml version="1.0" encoding="UTF-8"?>
<ns2:test-suite xmlns:ns2="urn:model.allure.qatools.yandex.ru" start="1464017648466" stop="1464017719277">
	<name>Process RRR at Bank Branch </name>
	<title>Process RRR at Bank Branch </title>
	<test-cases>
		<test-case start="1464017648466" stop="1464017719276" status="failed">
			<name>Insert RRR for Processing</name>
			<title>Insert RRR for Processing</title>
			<description></description>
			<labels>
			</labels>
			<steps>
			</steps>
			<attachments>
				<attachment title="Screenshot" source="821f11ff-e9b5-4127-b13d-2b15642f1835-attachment.png" type="image/png" size="69075"/>
			</attachments>
			<failure>
				<message>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.</message>
				<stack-trace>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
    at [object Object]._onTimeout (C:\Users\Samson\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1909:23)
    at Timer.listOnTimeout (timers.js:92:15)</stack-trace>
			</failure>
		</test-case>
	</test-cases>
</ns2:test-suite>